### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'childNodes')

### ISSUE THREAD

**Issue by zubayrali** [hilverd/glossary-page-template#1]
It keeps throwing this error as I try to add an item. Sometimes I cannot even Save the item, it just gets stuck there until I terminate the server.

Thanks for making this tool, I plan on using this as my Vocabulary Journal. Cheers : ) 

![image](https://user-images.githubusercontent.com/31969517/176630241-c8705d5d-0b38-4c97-9ad5-cc37e3ac25ba.png)

**Comment by hilverd** [comment]
So just to confirm -- this happens when you click "Save" to add a new item? And the server doesn't show any errors? Can you maybe share the HTML file (or some minimal example where this happens) so I can try to reproduce the problem?

**Comment by zubayrali** [comment]
I downloaded `empty.html` and yes, it happens only when I try to add a new item, it also happens when I edit the about section.
It happens for sure when I try to add a new term and save it without filling the second term field. Its a weird glitch I am not sure what exactly is causing it.

![image](https://user-images.githubusercontent.com/31969517/176868985-2026910f-27d9-488b-9eee-3121087c98fe.png)

**Comment by zubayrali** [comment]
About your first question - is the server supposed to show any errors? I only checked the browser's console, there are no errors on the terminal.

I ran using `sed -n '/START OF editor.js$/,$p' empty.html | FILE=empty.html node`

**Comment by hilverd** [comment]
I have tried to reproduce this but no luck so far. I've tried with Safari/Chrome/Firefox on macOS and with Chrome/Firefox on Linux. Can you let me know which OS and browser you are using?

**Comment by zubayrali** [comment]
Hey, sorry I forgot to mention this information earlier, it's:
Version 1.40.107 Chromium: 103.0.5060.53 (Official Build) (64-bit)
Ubuntu 20.04.4 LTS x86_64  
5.13.0-51-generic

**Comment by zubayrali** [comment]
I am not facing this issue anymore after downloading a new `empty.html`
