### ISSUE TITLE
Would it be possible to get the ability to add links?

### ISSUE THREAD

**Issue by dolkra** [hilverd/glossary-page-template#5]
Hi I love this template and I want to write a url-rich documentation, but I found it wouldn't work if I put something in like `<a href="https://www.w3schools.com">Visit W3Schools</a>` , would you consider add that kind of functionality? Thank you, it is a simple and elegant project

**Comment by hilverd** [comment]
If you [upgrade to v2.0.0](https://github.com/hilverd/glossary-page-template/releases/tag/v2.0.0) and switch to the Markdown-based syntax, then you can add links like this:

```
[Visit W3Schools](https://www.w3schools.com)
```

(The `a` tag also works but it currently gets rendered as a block instead of inline, I'll need to look into that.)
