### ISSUE TITLE
Need help to edit the html file

### ISSUE THREAD

**Issue by jeffwins** [hilverd/glossary-page-template#7]
This is really an elegant solution to make a glossary page. I see a lot of potential here. After downloading the file and installing node.js on my Windows 10 machine. I couldn't wait to fire up the following command on my cygwin terminal. Here is the command:

$ sed -n '/START OF editor.js$/,$p' glossary.html | FILE=glossary.html node
Server started at http://localhost:3003

Then I open the browser:
http://localhost:3003/glossary.html

I can't find anywhere I can edit/add/delete the glossary terms. 
![No Editing Option](https://user-images.githubusercontent.com/41946920/218335881-3beb5d85-f634-4ead-a10b-54740035e2dd.jpg)

Can someone shed some light here, please? I know the author recommends MacOS or Linux, which I do not have access to. Instead, I hope I can edit it on Windows and then deploy it to our hosting service. 

On the other hand, can someone show how I may hide the 'EXPORT' option which shows in the top right corner? 

Thanks.

Jeff Jiang

**Comment by hilverd** [comment]
Thanks for your feedback!

I would also like to know how to run the editor on Windows (I just don't have it on any of my machines at the moment). Maybe someone will post the answer here, if not then I'll try to find out myself.

There is currently no setting for hiding the "Export" menu so I'll add one, hopefully soon.

**Comment by hilverd** [comment]
Actually -- does the URL http://localhost:3003/ work for you, instead of http://localhost:3003/glossary.html?

**Comment by jeffwins** [comment]
Holy. Yes, http://localhost:3003/ works with the editing option. Thanks a bunch. 
![Editing Option](https://user-images.githubusercontent.com/41946920/218339205-1575060d-958f-43a0-93e2-9df6835b836d.jpg)

Jeff

**Comment by hilverd** [comment]
If you [upgrade to v2.0.0](https://github.com/hilverd/glossary-page-template/releases/tag/v2.0.0), then you'll be able to hide the "Export" menu using the settings near the top of the page.
