### ISSUE TITLE
Numbers, their positions and "hide order"

### ISSUE THREAD

**Issue by the-real-graybags** [hilverd/glossary-page-template#9]
Hi,

Great project, really easy to use, thank you so much for creating it.  Just a couple of things...

My glossary items include numbers (i.e. 3040) - is there a way to make them appear at the top of the glossary?   Currently they appear at the bottom. 

Also,  if my numbers have a letter in (654n for example), they get sorted with the "n's".  is there a way to stop that and force them to still be a number?

Finally, is there a way I can hide the "order items" stuff at the top?  Something like the way you can hide "Export" etc. would be great.

Thanks.

**Comment by hilverd** [comment]
Thanks!

I can make it so that "3040" and "654n" would both appear at the beginning of the item list, and in the index they would be grouped under a label "0–9" at the top (or at least before "A", "B" etc.). I agree that this seems better than the current behaviour that you mentioned. Does that sound OK?

Regarding the ability to hide "order items", sure I can add a toggle for that under Settings.

I'm currently working towards version 4 of the template which would add support for tags and some related improvements. That's taking a while so I'll have to see if I do the above changes before releasing that new major version or after...

**Comment by the-real-graybags** [comment]
Absolutely fantastic news! If you could do that it would be great. Thanks 😁

**Comment by hilverd** [comment]
I've tried to address this in version 3.8.0 which I've just released. Would you mind trying it out? If it looks good then I'll close this issue.

**Comment by the-real-graybags** [comment]
sorry, what do I need to download to test this?  is it just the latest glossary.js and glossary.css or or am I missing something here?

**Comment by hilverd** [comment]
In your `glossary.html` file, what do the tags at the end of the `<head>` element look like? If it's

```
<script type="module" crossorigin src="https://glstatic.net/glossary-page-template@3/glossary.min.js"></script>
<link rel="stylesheet" crossorigin href="https://glstatic.net/glossary-page-template@3/glossary.min.css">
```

then that should download the new version automatically. It may take up to one day (that's how long it's cached for) or you could try doing a "hard refresh" in your browser.

Alternatively you can point to a specific version in the tags, e.g. by changing the `3` to `3.8.0` like this:

```
<script type="module" crossorigin src="https://glstatic.net/glossary-page-template@3.8.0/glossary.min.js"></script>
<link rel="stylesheet" crossorigin href="https://glstatic.net/glossary-page-template@3.8.0/glossary.min.css">
```

See also https://github.com/hilverd/glossary-page-template#static-assets.

Does that make sense? I've been thinking that the instructions in the README might not be clear enough about this.

**Comment by the-real-graybags** [comment]
You're right, it just needed the hard refresh. The 0-9 is there and the numbers are at the top.  This is so much better for me personally, thanks again for doing it. Just the "order items" row to hide if that's possible, but there's no rush for that.

I really appreciate you doing this, thanks again.

**Comment by hilverd** [comment]
There should be a toggle for "Show 'Order items' buttons" under Settings as part of the new version -- is it appearing?

**Comment by the-real-graybags** [comment]
I can't see "Settings" anywhere - where is that?

**Comment by hilverd** [comment]
The same place where you can hide the Export menu -- see screenshot below (click Settings to expand). Or did you change that in the HTML directly? In that case you can add a `data-enable-order-items-buttons="false"` attribute next to the `data-enable-export-menu=...` attribute. In any case, the Settings menu should be there when you're in "editor mode". If it's not then there's a bug.

<img width="976" alt="settings" src="https://github.com/hilverd/glossary-page-template/assets/551077/5df8d8cb-dc0a-47a7-9e99-c6d18b389cd5">

**Comment by the-real-graybags** [comment]
I hid all that in the HTML and I'm not using this in "editor mode" at all.  I've added the data-enable-order-items-buttons="false" and it's gone.  Great, thanks 🥇
